mysql:
  # 这里无需更改，脚本会替换
  db: DBNAME
  host: localhost
  # 这里无需更改，脚本会替换
  password: PASSWD
  port: 3306
  user: root
  tls: false

redis:
  host: localhost
  port: 6379
  db: 0
  password: ""


secret: secret
serve_static: true

server:
  port: 8094
system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5
